In [3]:
import numpy as np
# N-dimensional array
# create an array with 1D array
array_1D=np.array([1,2,3,4,5])
print("1D array:",array_1D)

1D array: [1 2 3 4 5]


In [4]:
#create a 2D array
array_2D=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print("2D array:",array_2D)

2D array: [[1 2 3 4 5]
 [6 7 8 9 0]]


In [5]:
#create a 3D array
array_3D=np.array([[[1,2,3,4,5],[6,7,8,9,0],[1,4,5,6,3]]])
print("3D array:",array_3D)

3D array: [[[1 2 3 4 5]
  [6 7 8 9 0]
  [1 4 5 6 3]]]


In [8]:
#create an array with ones
array_ones=np.ones((2,4))
print("array with ones",array_ones)

array with ones [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
#create an array with zeros
array_zeros=np.zeros((3,3))
print("array with zeros",array_zeros)


array with zeros [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# create an array with perticular range
array_range=np.arange(10)
print("array with a range",array_range)

array with a range [0 1 2 3 4 5 6 7 8 9]
